const AddReviewActionsConstants = {
    UPDATE_STATE_FIELD: 'UPDATE_STATE_FIELD',
    SUGGEST_LOCATION:'SUGGEST_LOCATION',
    SUBMIT_REVIEW:'SUBMIT_REVIEW',
    MISSING_REVIEW_FIELDS:'MISSING_REVIEW_FIELDS',
    SUBMIT_REVIEW_FAILURE:'SUBMIT_REVIEW_FAILURE',
    SUBMIT_REVIEW_SUCCEED:'SUBMIT_REVIEW_SUCCEED',
    ADD_REVIEW_FAILURE:'ADD_REVIEW_FAILURE',
    VALIDATE_LOCATION: 'VALIDATE_LOCATION',
    CLEAR_FIELDS: 'CLEAR_FIELDS',
    INIT_REVIEW_MESSAGE: 'INIT_REVIEW_MESSAGE',
};

export { AddReviewActionsConstants };
