const AddReviewActionsConstants = {
    UPDATE_STATE_FIELD: 'UPDATE_STATE_FIELD',
    SUGGEST_LOCATION:'SUGGEST_LOCATION',
    SUBMIT_REVIEW:'SUBMIT_REVIEW',
    MISSING_FIELD:'MISSING_FIELD',
    SUBMIT_REVIEW_FAILURE:'SUBMIT_REVIEW_FAILURE',
    SUBMIT_REVIEW_SUCCEED:'SUBMIT_REVIEW_SUCCEED',
    ADD_REVIEW_FAILURE:'ADD_REVIEW_FAILURE',
    VALIDATE_LOCATION: 'VALIDATE_LOCATION',
};

export { AddReviewActionsConstants };
