const AppActionsConstants = {
    CONNECT_USER: 'CONNECT_USER',
    CHECK_TOKEN: 'CHECK_TOKEN',
    APP_FAILURE: 'APP_FAILURE',
    DISCONNECT_USER: 'DISCONNECT_USER',
    LOAD_CITIES: 'LOAD_CITIES',
    LOAD_USERS: 'LOAD_USERS',
    LOAD_RESTAURANTS:'LOAD_RESTAURANTS',
    LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',
    LOAD_RESTAURANTS_SUCCESS: 'LOAD_RESTAURANTS_SUCCESS',
    LOAD_CITIES_SUCCESS: 'LOAD_CITIES_SUCCESS',
    UPDATE_REVIEW_AFTER_SUBMIT: 'UPDATE_REVIEW_AFTER_SUBMIT',
    UPDATE_USER_AFTER_SUBMIT: 'UPDATE_USER_AFTER_SUBMIT',
    SET_ACTIVE: 'SET_ACTIVE',
    SUBMIT_EDIT_REVIEW_FAILURE:'SUBMIT_EDIT_REVIEW_FAILURE',
    SUBMIT_EDIT_REVIEW_SUCCEED:'SUBMIT_EDIT_REVIEW_SUCCEED',
    RESTAURANTS_FAILURE: 'RESTAURANTS_FAILURE'

};

export { AppActionsConstants}
