const ViewProfilePageActionsConstants = {
    TOGGLE_FORM: 'TOGGLE_FORM',
    UPDATE_STATE_FIELD: 'UPDATE_STATE_FIELD',
    RESTAURANTS_FAILURE: 'RESTAURANTS_FAILURE',
    VIEW_REVIEWS: 'VIEW_REVIEWS',
    EDIT_REVIEW: 'EDIT_REVIEW',
    SUBMIT_EDIT_REVIEW: 'SUBMIT_EDIT_REVIEW',
    EDIT_PROFILE: 'EDIT_PROFILE',
    VALIDATE_USERNAME: 'VALIDATE_USERNAME',
    VALIDATE_ACTION_SUCCESS: 'VALIDATE_ACTION_SUCCESS',
    VALIDATE_ACTION_FAILURE: 'VALIDATE_ACTION_FAILURE',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    SUGGEST_LOCATION: 'SUGGEST_LOCATION',
    SUBMIT_USER: 'SUBMIT_USER',
    SUBMIT_USER_SUCCESS: 'SUBMIT_USER_SUCCESS',
    VALIDATE_LOCATION: 'VALIDATE_LOCATION',
    MISSING_FIELDS: 'MISSING_FIELDS',
    SHOW_EDIT_PROFILE: 'SHOW_EDIT_PROFILE',
    UPDATE_PASSWORD:'UPDATE_PASSWORD',
    INIT_VIEW_PROFILE_MESSAGE: 'INIT_VIEW_PROFILE_MESSAGE',
};

export { ViewProfilePageActionsConstants };
