const ViewProfilePageActionsConstants = {
    TOGGLE_FORM: 'TOGGLE_FORM',
    UPDATE_STATE_FIELD: 'UPDATE_STATE_FIELD',
    VIEW_REVIEWS: 'VIEW_REVIEWS',
    EDIT_PROFILE: 'EDIT_PROFILE',
    VALIDATE_EDIT_USERNAME: 'VALIDATE_EDIT_USERNAME',
    VALIDATE_EDIT_ACTION_SUCCESS: 'VALIDATE_EDIT_ACTION_SUCCESS',
    VALIDATE_EDIT_ACTION_FAILURE: 'VALIDATE_EDIT_ACTION_FAILURE',
    SUGGEST_LOCATION: 'SUGGEST_LOCATION',
    SUBMIT_EDIT_USER: 'SUBMIT_EDIT_USER',
    VALIDATE_LOCATION: 'VALIDATE_LOCATION',
    MISSING_FIELDS: 'MISSING_FIELDS',
    SHOW_EDIT_PROFILE: 'SHOW_EDIT_PROFILE',
    UPDATE_PASSWORD:'UPDATE_PASSWORD',
    INIT_VIEW_PROFILE_MESSAGE: 'INIT_VIEW_PROFILE_MESSAGE',
    SUBMIT_EDIT_USER_SUCCESS: 'SUBMIT_EDIT_USER_SUCCESS',
    SUBMIT_EDIT_USER_FAILURE: 'SUBMIT_EDIT_USER_FAILURE',
};

export { ViewProfilePageActionsConstants };
