const RegisterPageActionsConstants = {
    UPDATE_STATE_FIELD: 'UPDATE_STATE_FIELD',
    VALIDATE_USERNAME: 'VALIDATE_USERNAME',
    VALIDATE_ACTION_SUCCESS: 'VALIDATE_ACTION_SUCCESS',
    VALIDATE_ACTION_FAILURE: 'VALIDATE_ACTION_FAILURE',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    SUGGEST_LOCATION: 'SUGGEST_LOCATION',
    SUBMIT_USER: 'SUBMIT_USER',
    SUBMIT_USER_SUCCESS: 'SUBMIT_USER_SUCCESS',
    VALIDATE_LOCATION: 'VALIDATE_LOCATION',
    MISSING_FIELDS: 'MISSING_FIELDS',
};

export { RegisterPageActionsConstants };
