const RegisterPageActionsConstants = {
    UPDATE_STATE_FIELD: 'UPDATE_STATE_FIELD',
    VALIDATE_REGISTER_USERNAME: 'VALIDATE_REGISTER_USERNAME',
    VALIDATE_REGISTER_ACTION_SUCCESS: 'VALIDATE_REGISTER_ACTION_SUCCESS',
    VALIDATE_REGISTER_ACTION_FAILURE: 'VALIDATE_REGISTER_ACTION_FAILURE',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    SUGGEST_LOCATION: 'SUGGEST_LOCATION',
    SUBMIT_USER: 'SUBMIT_USER',
    SUBMIT_USER_SUCCESS: 'SUBMIT_USER_SUCCESS',
    VALIDATE_LOCATION: 'VALIDATE_LOCATION',
    MISSING_REGISTER_FIELDS: 'MISSING_REGISTER_FIELDS',
    INIT_REGISTER_MESSAGE: 'INIT_REGISTER_MESSAGE'
};

export { RegisterPageActionsConstants };
