const RegisterPageActionsConstants = {
    UPDATE_STATE_FIELD: 'UPDATE_STATE_FIELD',
    VALIDATE_USERNAME: 'VALIDATE_USERNAME',
    VALIDATE_ACTION_SUCCESS: 'VALIDATE_ACTION_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    SUGGEST_LOCATION: 'SUGGEST_LOCATION',
    SUBMIT_USER: 'SUBMIT_USER',
    SUBMIT_USER_SUCCESS: 'SUBMIT_USER_SUCCESS'
};

export { RegisterPageActionsConstants };
