const RestaurantsActionsConstants = {
    TOGGLE_FORM: 'TOGGLE_FORM',
    UPDATE_STATE_FIELD: 'UPDATE_STATE_FIELD',
    UPDATE_SLIDER_FIELD: 'UPDATE_SLIDER_FIELD',
    RESTAURANTS_FAILURE: 'RESTAURANTS_FAILURE',
    VIEW_REVIEWS: 'VIEW_REVIEWS',
    EDIT_REVIEW: 'EDIT_REVIEW',
    SUBMIT_EDIT_REVIEW: 'SUBMIT_EDIT_REVIEW',

    DELETE_REVIEW: 'DELETE_REVIEW',
    DELETE_REVIEW_SUCCEED:'DELETE_REVIEW_SUCCEED',
    DELETE_REVIEW_FAILURE: 'DELETE_REVIEW_FAILURE',
    UPDATE_RESTAURANTS_TO_SHOW: 'UPDATE_RESTAURANTS_TO_SHOW',
    UPDATE_REST_SEARCH_VALUE: 'UPDATE_REST_SEARCH_VALUE',
    UPDATE_SEARCH_REVIEW: 'UPDATE_SEARCH_REVIEW',
    UPDATE_REVIEWS_TO_SHOW: 'UPDATE_REVIEWS_TO_SHOW',
    UPDATE_REVIEW_SLIDER_FIELD: 'UPDATE_REVIEW_SLIDER_FIELD',
    UPDATE_REVIEW_SEARCH_VALUE: 'UPDATE_REVIEW_SEARCH_VALUE',
    UPDATE_CLOSER_BETTER_SLIDER_FIELD: 'UPDATE_CLOSER_BETTER_SLIDER_FIELD',
    SHOW_REVIEWS: 'SHOW_REVIEWS',
    SUGGEST_IN_RESTAURANTS: 'SUGGEST_IN_RESTAURANTS',
    INIT_TO_SHOW: 'INIT_TO_SHOW',
    UPDATE_REVIEWS_TO_SHOW_AFTER_DELETE: 'UPDATE_REVIEWS_TO_SHOW_AFTER_DELETE',
};

export { RestaurantsActionsConstants };
