const RestaurantsActionsConstants = {
    TOGGLE_FORM: 'TOGGLE_FORM',
    UPDATE_STATE_FIELD: 'UPDATE_STATE_FIELD',
    SUGGEST_LOCATION: 'SUGGEST_LOCATION',
    SUBMIT_RESTAURANT: 'SUBMIT_RESTAURANT',
    RESTAURANTS_FAILURE: 'RESTAURANTS_FAILURE',
    SUBMIT_RESTAURANT_FAILURE: 'SUBMIT_RESTAURANT_FAILURE',
    SUBMIT_RESTAURANT_SUCCEED: 'SUBMIT_RESTAURANT_SUCCEED',
    MISSING_FIELD: 'MISSING_FIELD',
};

export { RestaurantsActionsConstants };
