const RestaurantsActionsConstants = {
    TOGGLE_FORM: 'TOGGLE_FORM',
    UPDATE_STATE_FIELD: 'UPDATE_STATE_FIELD',
    RESTAURANTS_FAILURE: 'RESTAURANTS_FAILURE',
    VIEW_REVIEWS: 'VIEW_REVIEWS',
    EDIT_REVIEW: 'EDIT_REVIEW',
    SUBMIT_EDIT_REVIEW: 'SUBMIT_EDIT_REVIEW',
    SUBMIT_EDIT_REVIEW_FAILURE:'SUBMIT_EDIT_REVIEW_FAILURE',
    SUBMIT_EDIT_REVIEW_SUCCEED:'SUBMIT_EDIT_REVIEW_SUCCEED',
    DELETE_REVIEW: 'DELETE_REVIEW',
    DELETE_REVIEW_SUCCEED:'DELETE_REVIEW_SUCCEED',
    DELETE_REVIEW_FAILURE: 'DELETE_REVIEW_FAILURE',
};

export { RestaurantsActionsConstants };
