const LogInPageActionsConstants = {
    UPDATE_STATE_FIELD: 'UPDATE_STATE_FIELD',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    VALIDATE_USER: 'VALIDATE_USER',
    FALSE_VALIDATE_USER: 'FALSE_VALIDATE_USER',
    SUCCESS_VALIDATE_USER: 'SUCCESS_VALIDATE_USER',
    MISSING_FIELD: 'MISSING_FIELD',
    INIT_ERROR_MESSAGE: 'INIT_ERROR_MESSAGE',
};

export { LogInPageActionsConstants };
