const UsersActionsConstants = {
    UPDATE_STATE_FIELD: 'UPDATE_STATE_FIELD',
    VIEW_REVIEWS: 'VIEW_REVIEWS',
    MOVE_TO_MY_PROFILE:'MOVE_TO_MY_PROFILE',
    MOVE_FROM_USERS:'MOVE_FROM_USERS',
    UPDATE_USERS_TO_SHOW: 'UPDATE_USERS_TO_SHOW',
    UPDATE_SEARCH_KEY: 'UPDATE_SEARCH_KEY',
    UPDATE_USER_SEARCH_VALUE:'UPDATE_USER_SEARCH_VALUE',
};

export {UsersActionsConstants };
