const ReviewActionsConstants = {
    TOGGLE_FORM: 'TOGGLE_FORM',
    UPDATE_STATE_FIELD: 'UPDATE_STATE_FIELD',
    UPDATE_SLIDER_FIELD: 'UPDATE_SLIDER_FIELD',
    VIEW_REVIEWS: 'VIEW_REVIEWS',
    EDIT_REVIEW: 'EDIT_REVIEW',
    SUBMIT_EDIT_REVIEW: 'SUBMIT_EDIT_REVIEW',
    SUBMIT_EDIT_REVIEW_FAILURE:'SUBMIT_EDIT_REVIEW_FAILURE',
    SUBMIT_EDIT_REVIEW_SUCCEED:'SUBMIT_EDIT_REVIEW_SUCCEED',
    DELETE_REVIEW: 'DELETE_REVIEW',
    DELETE_REVIEW_SUCCEED:'DELETE_REVIEW_SUCCEED',
    DELETE_REVIEW_FAILURE: 'DELETE_REVIEW_FAILURE',
    UPDATE_RESTAURANTS_TO_SHOW: 'UPDATE_RESTAURANTS_TO_SHOW',
    UPDATE_REST_SEARCH_VALUE: 'UPDATE_REST_SEARCH_VALUE',
    UPDATE_SEARCH_REVIEW: 'UPDATE_SEARCH_REVIEW',
    UPDATE_REVIEWS_TO_SHOW: 'UPDATE_REVIEWS_TO_SHOW',
    UPDATE_REVIEW_SLIDER_FIELD: 'UPDATE_REVIEW_SLIDER_FIELD',
    UPDATE_REVIEW_SEARCH_VALUE: 'UPDATE_REVIEW_SEARCH_VALUE',
};

export { ReviewActionsConstants };
