const TopBarActionsConstants = {
    SET_ACTIVE: 'SET_ACTIVE',
    UPDATE_FORM_WIDTH: 'UPDATE_FORM_WIDTH',
    UPDATE_NAME: 'UPDATE_NAME',
    LOAD_REVIEWS:'LOAD_REVIEWS',
    ADD_REVIEW_ACTION_SUCCESS:'ADD_REVIEW_ACTION_SUCCESS',
    ADD_REVIEW_ACTION_FAILURE:'ADD_REVIEW_ACTION_FAILURE'

};

export { TopBarActionsConstants };
